files:
  - source: /locales/en/translation.json
    translation: /locales/%locale%/translation.json
    languages_mapping:
      locale:
        ja: ja
        it: it
        pt-BR: pt-BR
  - source: /src-tauri/locales/en.yml
    translation: /src-tauri/locales/%locale%.yml
    languages_mapping:
      locale:
        ja: ja
        it: it
        pt-BR: pt-BR
