CREATE TABLE IF NOT EXISTS servers(
  id INTEGER PRIMARY KEY,
  domain TEXT NOT NULL,
  base_url TEXT NOT NULL,
  favicon TEXT DEFAULT NULL,
  account_id INTEGER UNIQUE DEFAULT NULL,
  FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS accounts(
  id INTEGER PRIMARY KEY,
  username TEXT NOT NULL,
  account_id TEXT NOT NULL,
  avatar TEXT DEFAULT NULL,
  client_id TEXT DEFAULT NULL,
  client_secret TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS timelines(
  id INTEGER PRIMARY KEY,
  server_id INTEGER NOT NULL,
  timeline TEXT NOT NULL,
  sort INTEGER UNIQUE NOT NULL,
  FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE
);
