name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Build
      working-directory: ./src-tauri
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./src-tauri
      run: cargo test --verbose
