name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: '20 14 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          minimum: 500
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[Auto update] Sponsors list"
          branch: auto-update/sponsors
          base: master
          delete-branch: true
          title: "[Auto update] Sponsors list"
